// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `clone`, `eq`, `fmt`
// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `effective`

/// Returns the engines this build can play audio with, in the order the settings list them.
List<AudioEngine> availableAudioEngines() =>
    RustLib.instance.api.crateApiAudioAvailableAudioEngines();

/// Returns the engine used when none has been chosen yet.
AudioEngine defaultAudioEngine() =>
    RustLib.instance.api.crateApiAudioDefaultAudioEngine();

/// Engine that plays the audio of a session.
///
/// Every variant exists on every platform so that the generated Dart type is the same
/// everywhere. Which engines a build can actually use is reported by
/// [`available_audio_engines`].
enum AudioEngine {
  /// The OpenAL sink of the core.
  openAl,

  /// Oboe, driven by this crate. Only available on Android.
  oboe,
}
