// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../error.dart';
import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Prepares the user directory of a profile before it is switched to, so a new profile can be
/// started without the core failing on missing folders.
Future<void> initializeStorage({required String location}) =>
    RustLib.instance.api.crateApiStorageInitializeStorage(location: location);
