// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/audio.dart';
import 'api/session.dart';
import 'api/storage.dart';

import 'dart:async';
import 'dart:convert';

import 'error.dart';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

import 'session.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiSessionInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.13.0';

  @override
  int get rustContentHash => 1293222700;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'azahar_rust',
        ioDirectory: '../azahar_rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  List<AudioEngine> crateApiAudioAvailableAudioEngines();

  AudioEngine crateApiAudioDefaultAudioEngine();

  Future<Uint8List> crateApiSessionDumpFcram();

  Future<BigInt> crateApiSessionFcramSize();

  Future<void> crateApiSessionInitApp();

  Future<void> crateApiStorageInitializeStorage({required String location});

  Future<void> crateApiSessionPauseGame();

  Future<Uint8List> crateApiSessionReadMemory({
    required int address,
    required int len,
  });

  Future<int> crateApiSessionReadU32({required int address});

  Future<void> crateApiSessionResumeGame();

  Future<void> crateApiSessionSetVolume({required double volume});

  Stream<SessionEvent> crateApiSessionStartGame({
    required String gamePath,
    required SessionOptions options,
  });

  Future<void> crateApiSessionStopGame({required bool persist});
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  List<AudioEngine> crateApiAudioAvailableAudioEngines() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 1)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_audio_engine,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiAudioAvailableAudioEnginesConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAudioAvailableAudioEnginesConstMeta =>
      const TaskConstMeta(debugName: "available_audio_engines", argNames: []);

  @override
  AudioEngine crateApiAudioDefaultAudioEngine() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 2)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_audio_engine,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiAudioDefaultAudioEngineConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAudioDefaultAudioEngineConstMeta =>
      const TaskConstMeta(debugName: "default_audio_engine", argNames: []);

  @override
  Future<Uint8List> crateApiSessionDumpFcram() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_azahar_error,
        ),
        constMeta: kCrateApiSessionDumpFcramConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSessionDumpFcramConstMeta =>
      const TaskConstMeta(debugName: "dump_fcram", argNames: []);

  @override
  Future<BigInt> crateApiSessionFcramSize() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_64,
          decodeErrorData: sse_decode_azahar_error,
        ),
        constMeta: kCrateApiSessionFcramSizeConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSessionFcramSizeConstMeta =>
      const TaskConstMeta(debugName: "fcram_size", argNames: []);

  @override
  Future<void> crateApiSessionInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSessionInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSessionInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  Future<void> crateApiStorageInitializeStorage({required String location}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(location, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_azahar_error,
        ),
        constMeta: kCrateApiStorageInitializeStorageConstMeta,
        argValues: [location],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiStorageInitializeStorageConstMeta =>
      const TaskConstMeta(
        debugName: "initialize_storage",
        argNames: ["location"],
      );

  @override
  Future<void> crateApiSessionPauseGame() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_azahar_error,
        ),
        constMeta: kCrateApiSessionPauseGameConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSessionPauseGameConstMeta =>
      const TaskConstMeta(debugName: "pause_game", argNames: []);

  @override
  Future<Uint8List> crateApiSessionReadMemory({
    required int address,
    required int len,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_32(address, serializer);
          sse_encode_u_32(len, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_azahar_error,
        ),
        constMeta: kCrateApiSessionReadMemoryConstMeta,
        argValues: [address, len],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSessionReadMemoryConstMeta => const TaskConstMeta(
    debugName: "read_memory",
    argNames: ["address", "len"],
  );

  @override
  Future<int> crateApiSessionReadU32({required int address}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_32(address, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_32,
          decodeErrorData: sse_decode_azahar_error,
        ),
        constMeta: kCrateApiSessionReadU32ConstMeta,
        argValues: [address],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSessionReadU32ConstMeta =>
      const TaskConstMeta(debugName: "read_u32", argNames: ["address"]);

  @override
  Future<void> crateApiSessionResumeGame() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_azahar_error,
        ),
        constMeta: kCrateApiSessionResumeGameConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSessionResumeGameConstMeta =>
      const TaskConstMeta(debugName: "resume_game", argNames: []);

  @override
  Future<void> crateApiSessionSetVolume({required double volume}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_f_32(volume, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_azahar_error,
        ),
        constMeta: kCrateApiSessionSetVolumeConstMeta,
        argValues: [volume],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSessionSetVolumeConstMeta =>
      const TaskConstMeta(debugName: "set_volume", argNames: ["volume"]);

  @override
  Stream<SessionEvent> crateApiSessionStartGame({
    required String gamePath,
    required SessionOptions options,
  }) {
    final events = RustStreamSink<SessionEvent>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_String(gamePath, serializer);
            sse_encode_box_autoadd_session_options(options, serializer);
            sse_encode_StreamSink_session_event_Sse(events, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 12,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: sse_decode_azahar_error,
          ),
          constMeta: kCrateApiSessionStartGameConstMeta,
          argValues: [gamePath, options, events],
          apiImpl: this,
        ),
      ),
    );
    return events.stream;
  }

  TaskConstMeta get kCrateApiSessionStartGameConstMeta => const TaskConstMeta(
    debugName: "start_game",
    argNames: ["gamePath", "options", "events"],
  );

  @override
  Future<void> crateApiSessionStopGame({required bool persist}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_bool(persist, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_azahar_error,
        ),
        constMeta: kCrateApiSessionStopGameConstMeta,
        argValues: [persist],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSessionStopGameConstMeta =>
      const TaskConstMeta(debugName: "stop_game", argNames: ["persist"]);

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  RustStreamSink<SessionEvent> dco_decode_StreamSink_session_event_Sse(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  AudioEngine dco_decode_audio_engine(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AudioEngine.values[raw as int];
  }

  @protected
  AzaharError dco_decode_azahar_error(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return AzaharError_SessionActive();
      case 1:
        return AzaharError_NoSession();
      case 2:
        return AzaharError_InvalidPath();
      case 3:
        return AzaharError_CreateFailed();
      case 4:
        return AzaharError_InvalidState();
      case 5:
        return AzaharError_Core(dco_decode_i_32(raw[1]));
      case 6:
        return AzaharError_InvalidAddress(
          address: dco_decode_u_32(raw[1]),
          len: dco_decode_u_32(raw[2]),
        );
      case 7:
        return AzaharError_LibraryLoad(dco_decode_String(raw[1]));
      case 8:
        return AzaharError_Audio(dco_decode_String(raw[1]));
      case 9:
        return AzaharError_Storage(dco_decode_String(raw[1]));
      case 10:
        return AzaharError_StorageCommit(dco_decode_list_String(raw[1]));
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  SessionOptions dco_decode_box_autoadd_session_options(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_session_options(raw);
  }

  @protected
  double dco_decode_f_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<AudioEngine> dco_decode_list_audio_engine(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_audio_engine).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  SessionEvent dco_decode_session_event(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return SessionEvent_ShaderProgress(
          stage: dco_decode_shader_stage(raw[1]),
          progress: dco_decode_u_64(raw[2]),
          max: dco_decode_u_64(raw[3]),
        );
      case 1:
        return SessionEvent_Texture(
          textureId: dco_decode_i_64(raw[1]),
          secondary: dco_decode_bool(raw[2]),
        );
      case 2:
        return SessionEvent_StateChanged(
          state: dco_decode_session_state(raw[1]),
        );
      case 3:
        return SessionEvent_Error(message: dco_decode_String(raw[1]));
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  SessionOptions dco_decode_session_options(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return SessionOptions(
      primaryWidth: dco_decode_i_32(arr[0]),
      primaryHeight: dco_decode_i_32(arr[1]),
      secondaryWidth: dco_decode_i_32(arr[2]),
      secondaryHeight: dco_decode_i_32(arr[3]),
      dualScreen: dco_decode_bool(arr[4]),
      audioEngine: dco_decode_audio_engine(arr[5]),
    );
  }

  @protected
  SessionState dco_decode_session_state(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return SessionState.values[raw as int];
  }

  @protected
  ShaderStage dco_decode_shader_stage(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ShaderStage.values[raw as int];
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  RustStreamSink<SessionEvent> sse_decode_StreamSink_session_event_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  AudioEngine sse_decode_audio_engine(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return AudioEngine.values[inner];
  }

  @protected
  AzaharError sse_decode_azahar_error(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        return AzaharError_SessionActive();
      case 1:
        return AzaharError_NoSession();
      case 2:
        return AzaharError_InvalidPath();
      case 3:
        return AzaharError_CreateFailed();
      case 4:
        return AzaharError_InvalidState();
      case 5:
        var var_field0 = sse_decode_i_32(deserializer);
        return AzaharError_Core(var_field0);
      case 6:
        var var_address = sse_decode_u_32(deserializer);
        var var_len = sse_decode_u_32(deserializer);
        return AzaharError_InvalidAddress(address: var_address, len: var_len);
      case 7:
        var var_field0 = sse_decode_String(deserializer);
        return AzaharError_LibraryLoad(var_field0);
      case 8:
        var var_field0 = sse_decode_String(deserializer);
        return AzaharError_Audio(var_field0);
      case 9:
        var var_field0 = sse_decode_String(deserializer);
        return AzaharError_Storage(var_field0);
      case 10:
        var var_field0 = sse_decode_list_String(deserializer);
        return AzaharError_StorageCommit(var_field0);
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  SessionOptions sse_decode_box_autoadd_session_options(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_session_options(deserializer));
  }

  @protected
  double sse_decode_f_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat32();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<AudioEngine> sse_decode_list_audio_engine(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <AudioEngine>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_audio_engine(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  SessionEvent sse_decode_session_event(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        var var_stage = sse_decode_shader_stage(deserializer);
        var var_progress = sse_decode_u_64(deserializer);
        var var_max = sse_decode_u_64(deserializer);
        return SessionEvent_ShaderProgress(
          stage: var_stage,
          progress: var_progress,
          max: var_max,
        );
      case 1:
        var var_textureId = sse_decode_i_64(deserializer);
        var var_secondary = sse_decode_bool(deserializer);
        return SessionEvent_Texture(
          textureId: var_textureId,
          secondary: var_secondary,
        );
      case 2:
        var var_state = sse_decode_session_state(deserializer);
        return SessionEvent_StateChanged(state: var_state);
      case 3:
        var var_message = sse_decode_String(deserializer);
        return SessionEvent_Error(message: var_message);
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  SessionOptions sse_decode_session_options(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_primaryWidth = sse_decode_i_32(deserializer);
    var var_primaryHeight = sse_decode_i_32(deserializer);
    var var_secondaryWidth = sse_decode_i_32(deserializer);
    var var_secondaryHeight = sse_decode_i_32(deserializer);
    var var_dualScreen = sse_decode_bool(deserializer);
    var var_audioEngine = sse_decode_audio_engine(deserializer);
    return SessionOptions(
      primaryWidth: var_primaryWidth,
      primaryHeight: var_primaryHeight,
      secondaryWidth: var_secondaryWidth,
      secondaryHeight: var_secondaryHeight,
      dualScreen: var_dualScreen,
      audioEngine: var_audioEngine,
    );
  }

  @protected
  SessionState sse_decode_session_state(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return SessionState.values[inner];
  }

  @protected
  ShaderStage sse_decode_shader_stage(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return ShaderStage.values[inner];
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_StreamSink_session_event_Sse(
    RustStreamSink<SessionEvent> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_session_event,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_audio_engine(AudioEngine self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_azahar_error(AzaharError self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case AzaharError_SessionActive():
        sse_encode_i_32(0, serializer);
      case AzaharError_NoSession():
        sse_encode_i_32(1, serializer);
      case AzaharError_InvalidPath():
        sse_encode_i_32(2, serializer);
      case AzaharError_CreateFailed():
        sse_encode_i_32(3, serializer);
      case AzaharError_InvalidState():
        sse_encode_i_32(4, serializer);
      case AzaharError_Core(field0: final field0):
        sse_encode_i_32(5, serializer);
        sse_encode_i_32(field0, serializer);
      case AzaharError_InvalidAddress(address: final address, len: final len):
        sse_encode_i_32(6, serializer);
        sse_encode_u_32(address, serializer);
        sse_encode_u_32(len, serializer);
      case AzaharError_LibraryLoad(field0: final field0):
        sse_encode_i_32(7, serializer);
        sse_encode_String(field0, serializer);
      case AzaharError_Audio(field0: final field0):
        sse_encode_i_32(8, serializer);
        sse_encode_String(field0, serializer);
      case AzaharError_Storage(field0: final field0):
        sse_encode_i_32(9, serializer);
        sse_encode_String(field0, serializer);
      case AzaharError_StorageCommit(field0: final field0):
        sse_encode_i_32(10, serializer);
        sse_encode_list_String(field0, serializer);
    }
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_session_options(
    SessionOptions self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_session_options(self, serializer);
  }

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat32(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_audio_engine(
    List<AudioEngine> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_audio_engine(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_session_event(SessionEvent self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case SessionEvent_ShaderProgress(
        stage: final stage,
        progress: final progress,
        max: final max,
      ):
        sse_encode_i_32(0, serializer);
        sse_encode_shader_stage(stage, serializer);
        sse_encode_u_64(progress, serializer);
        sse_encode_u_64(max, serializer);
      case SessionEvent_Texture(
        textureId: final textureId,
        secondary: final secondary,
      ):
        sse_encode_i_32(1, serializer);
        sse_encode_i_64(textureId, serializer);
        sse_encode_bool(secondary, serializer);
      case SessionEvent_StateChanged(state: final state):
        sse_encode_i_32(2, serializer);
        sse_encode_session_state(state, serializer);
      case SessionEvent_Error(message: final message):
        sse_encode_i_32(3, serializer);
        sse_encode_String(message, serializer);
    }
  }

  @protected
  void sse_encode_session_options(
    SessionOptions self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.primaryWidth, serializer);
    sse_encode_i_32(self.primaryHeight, serializer);
    sse_encode_i_32(self.secondaryWidth, serializer);
    sse_encode_i_32(self.secondaryHeight, serializer);
    sse_encode_bool(self.dualScreen, serializer);
    sse_encode_audio_engine(self.audioEngine, serializer);
  }

  @protected
  void sse_encode_session_state(SessionState self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_shader_stage(ShaderStage self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }
}
