// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'session.freezed.dart';

@freezed
sealed class SessionEvent with _$SessionEvent {
  const SessionEvent._();

  const factory SessionEvent.shaderProgress({
    required ShaderStage stage,
    required BigInt progress,
    required BigInt max,
  }) = SessionEvent_ShaderProgress;
  const factory SessionEvent.texture({
    required PlatformInt64 textureId,
    required bool secondary,
  }) = SessionEvent_Texture;
  const factory SessionEvent.stateChanged({required SessionState state}) =
      SessionEvent_StateChanged;
  const factory SessionEvent.error({required String message}) =
      SessionEvent_Error;
}

/// Size of the screen textures of a session.
class SessionOptions {
  final int primaryWidth;
  final int primaryHeight;
  final int secondaryWidth;
  final int secondaryHeight;
  final bool dualScreen;

  const SessionOptions({
    required this.primaryWidth,
    required this.primaryHeight,
    required this.secondaryWidth,
    required this.secondaryHeight,
    required this.dualScreen,
  });

  @override
  int get hashCode =>
      primaryWidth.hashCode ^
      primaryHeight.hashCode ^
      secondaryWidth.hashCode ^
      secondaryHeight.hashCode ^
      dualScreen.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SessionOptions &&
          runtimeType == other.runtimeType &&
          primaryWidth == other.primaryWidth &&
          primaryHeight == other.primaryHeight &&
          secondaryWidth == other.secondaryWidth &&
          secondaryHeight == other.secondaryHeight &&
          dualScreen == other.dualScreen;
}

/// Lifecycle state of a session.
enum SessionState { idle, running, paused }

/// Phase of the shader cache preparation reported by the core.
enum ShaderStage { prepare, decompile, build, complete }
